## Load your data (for public sharing)

---

In [1]:
# 한글 원본
import gdown
import pandas as pd

# Upload the data file to your Google Drive, and turn on the link sharing
# Replace 'YOUR_FILE_ID' with the actual file ID from your public Google Drive link e.g., "https://drive.google.com/file/d/YOUR_FILE_ID/view?usp=sharing"
file_id = "17dFcGsd8TG0ji-LOedZmcGgST5rWWqa2"

# Name for the downloaded file in Colab
output_filename = 'result.xlsx'

gdown.download(id=file_id, output=output_filename, quiet=False)

print(f"File '{output_filename}' downloaded successfully!")

# Now you can load it with pandas
df_raw = pd.read_excel(output_filename)
display(df_raw.head())

Downloading...
From: https://drive.google.com/uc?id=17dFcGsd8TG0ji-LOedZmcGgST5rWWqa2
To: /content/result.xlsx
100%|██████████| 16.2M/16.2M [00:00<00:00, 65.9MB/s]

File 'result.xlsx' downloaded successfully!

,연령,성별,상황키워드,신체질환,감정_대분류,감정_소분류,사람문장1,시스템문장1,사람문장2,시스템문장2,사람문장3,시스템문장3,사람문장_통합,추론_감성_점수
0,청년,남성,"진로,취업,직장",해당없음,불안,두려운,이번 프로젝트에서 발표를 하는데 내가 실수하는 바람에 우리 팀이 감점을 받았어. 너...,실수하시다니 정말 미안한 마음이 크겠어요.,내 능력이 부족한 거 같은데 그만 다녀야 될거같아.,능력을 올리려면 어떤 방법이 있을까요?,퇴근 후 여가에 회사 일을 더 열심히 해서 피해가 가지 않도록 해야겠어.,꼭 좋은 결과 있길 바라요.,이번 프로젝트에서 발표를 하는데 내가 실수하는 바람에 우리 팀이 감점을 받았어. 너...,-0.682257
1,청년,남성,"진로,취업,직장",해당없음,불안,두려운,회사에서 중요한 프로젝트를 혼자 하게 됐는데 솔직히 두렵고 무서워.,큰 프로젝트를 혼자 하셔서 고민이 많겠네요.,나에게 너무 크게 느껴지는 중요한 프로젝트라 버거운 느낌이 들어.,프로젝트를 잘하시기 위해서 어떤 걸 할 수 있나요?,동료 직원에게 도움을 요청해서 같이 해결해야겠어.,동료 직원에게 도움을 요청하기로 하셨군요.,회사에서 중요한 프로젝트를 혼자 하게 됐는데 솔직히 두렵고 무서워. 나에게 너무 크...,-0.688704
2,청년,남성,"진로,취업,직장",해당없음,불안,두려운,상사가 너무 무섭게 생겨서 친해지는 게 너무 두려워.,직장 상사가 무섭게 생기셔서 친해지는 게 어렵군요.,무섭게 생겼는데도 업무를 보려면 친해져야 할 것 같단말이야.,상사분과 친해질 수 있는 방법은 무엇이 있을까요?,먼저 다가가서 말을 걸어볼게.,직장 상사와 친해지시면 좋겠네요.,상사가 너무 무섭게 생겨서 친해지는 게 너무 두려워. 무섭게 생겼는데도 업무를 보려...,-0.586495
3,청년,남성,"진로,취업,직장",해당없음,불안,두려운,이번에 힘들게 들어간 첫 직장이거든. 첫 직장이라서 그런지 너무 긴장된다.,첫 직장이라서 정말 떨리시고 긴장되실 것 같아요.,첫 직장이어서 잘 적응을 할 수 있을지 모르겠어.,잘 적응 하시려면 무엇을 할 수 있을까요?,직장 동료와 상사들이랑 친하게 지내야겠어.,직장에 잘 적응하시길 바라요.,이번에 힘들게 들어간 첫 직장이거든. 첫 직장이라서 그런지 너무 긴장된다. 첫 직장...,-0.461388
4,청년,남성,"진로,취업,직장",해당없음,불안,두려운,직장에서 동료들이랑 관계가 안 좋아질까 봐 걱정돼.,직장 사람들 관계에 대해서 고민이시군요.,내가 낯가림이 심해서 친해질 수 있을지 모르겠어.,직장 사람들과 친해지려면 무슨 방법이 있을까요?,서로 같은 취미를 공유하고 얘기를 나누다 보면 친해질 수 있을 거 같아.,직장 사람들과 좋은 관계를 가지시길 응원해요.,직장에서 동료들이랑 관계가 안 좋아질까 봐 걱정돼. 내가 낯가림이 심해서 친해질 수...,-0.462224

In [2]:
# 영어 번역 추가
import gdown
import pandas as pd

# Upload the data file to your Google Drive, and turn on the link sharing
# Replace 'YOUR_FILE_ID' with the actual file ID from your public Google Drive link e.g., "https://drive.google.com/file/d/YOUR_FILE_ID/view?usp=sharing"
file_id = "11pouwiEWKxEB3B26Njp3Qx_PfpK8RJSl"

# Name for the downloaded file in Colab
output_filename = 't_result.xlsx'

gdown.download(id=file_id, output=output_filename, quiet=False)

print(f"File '{output_filename}' downloaded successfully!")

# Now you can load it with pandas
df_raw = pd.read_excel(output_filename)
display(df_raw.head())

Downloading...
From: https://drive.google.com/uc?id=11pouwiEWKxEB3B26Njp3Qx_PfpK8RJSl
To: /content/t_result.xlsx
100%|██████████| 20.0M/20.0M [00:00<00:00, 50.8MB/s]

File 't_result.xlsx' downloaded successfully!

,연령,성별,상황키워드,신체질환,감정_대분류,감정_소분류,사람문장1,시스템문장1,사람문장2,시스템문장2,사람문장3,시스템문장3,사람문장_통합,추론_감성_점수,영어문장_통합
0,청년,남성,"진로,취업,직장",해당없음,불안,두려운,이번 프로젝트에서 발표를 하는데 내가 실수하는 바람에 우리 팀이 감점을 받았어. 너...,실수하시다니 정말 미안한 마음이 크겠어요.,내 능력이 부족한 거 같은데 그만 다녀야 될거같아.,능력을 올리려면 어떤 방법이 있을까요?,퇴근 후 여가에 회사 일을 더 열심히 해서 피해가 가지 않도록 해야겠어.,꼭 좋은 결과 있길 바라요.,이번 프로젝트에서 발표를 하는데 내가 실수하는 바람에 우리 팀이 감점을 받았어. 너...,-0.682257,"During the presentation on this project, I mad..."
1,청년,남성,"진로,취업,직장",해당없음,불안,두려운,회사에서 중요한 프로젝트를 혼자 하게 됐는데 솔직히 두렵고 무서워.,큰 프로젝트를 혼자 하셔서 고민이 많겠네요.,나에게 너무 크게 느껴지는 중요한 프로젝트라 버거운 느낌이 들어.,프로젝트를 잘하시기 위해서 어떤 걸 할 수 있나요?,동료 직원에게 도움을 요청해서 같이 해결해야겠어.,동료 직원에게 도움을 요청하기로 하셨군요.,회사에서 중요한 프로젝트를 혼자 하게 됐는데 솔직히 두렵고 무서워. 나에게 너무 크...,-0.688704,My boss looks so scary that I'm afraid to get ...
2,청년,남성,"진로,취업,직장",해당없음,불안,두려운,상사가 너무 무섭게 생겨서 친해지는 게 너무 두려워.,직장 상사가 무섭게 생기셔서 친해지는 게 어렵군요.,무섭게 생겼는데도 업무를 보려면 친해져야 할 것 같단말이야.,상사분과 친해질 수 있는 방법은 무엇이 있을까요?,먼저 다가가서 말을 걸어볼게.,직장 상사와 친해지시면 좋겠네요.,상사가 너무 무섭게 생겨서 친해지는 게 너무 두려워. 무섭게 생겼는데도 업무를 보려...,-0.586495,My boss looks so scary that I'm afraid to get ...
3,청년,남성,"진로,취업,직장",해당없음,불안,두려운,이번에 힘들게 들어간 첫 직장이거든. 첫 직장이라서 그런지 너무 긴장된다.,첫 직장이라서 정말 떨리시고 긴장되실 것 같아요.,첫 직장이어서 잘 적응을 할 수 있을지 모르겠어.,잘 적응 하시려면 무엇을 할 수 있을까요?,직장 동료와 상사들이랑 친하게 지내야겠어.,직장에 잘 적응하시길 바라요.,이번에 힘들게 들어간 첫 직장이거든. 첫 직장이라서 그런지 너무 긴장된다. 첫 직장...,-0.461388,This is my first job with great difficulty. Ma...
4,청년,남성,"진로,취업,직장",해당없음,불안,두려운,직장에서 동료들이랑 관계가 안 좋아질까 봐 걱정돼.,직장 사람들 관계에 대해서 고민이시군요.,내가 낯가림이 심해서 친해질 수 있을지 모르겠어.,직장 사람들과 친해지려면 무슨 방법이 있을까요?,서로 같은 취미를 공유하고 얘기를 나누다 보면 친해질 수 있을 거 같아.,직장 사람들과 좋은 관계를 가지시길 응원해요.,직장에서 동료들이랑 관계가 안 좋아질까 봐 걱정돼. 내가 낯가림이 심해서 친해질 수...,-0.462224,I'm worried that my relationship with my colle...

In [1]:
# Q1까지 수행
import gdown
import pandas as pd

# Upload the data file to your Google Drive, and turn on the link sharing
# Replace 'YOUR_FILE_ID' with the actual file ID from your public Google Drive link e.g., "https://drive.google.com/file/d/YOUR_FILE_ID/view?usp=sharing"
file_id = "1SqVxtbB3-UShQ2x2icBcvL6qMe-Qo3oi"

# Name for the downloaded file in Colab
output_filename = 'ct_result.xlsx'

gdown.download(id=file_id, output=output_filename, quiet=False)

print(f"File '{output_filename}' downloaded successfully!")

# Now you can load it with pandas
df_raw = pd.read_excel(output_filename)
display(df_raw.head())

KeyboardInterrupt:

In [ ]:
# Q2까지 수행
import gdown
import pandas as pd

# Upload the data file to your Google Drive, and turn on the link sharing
# Replace 'YOUR_FILE_ID' with the actual file ID from your public Google Drive link e.g., "https://drive.google.com/file/d/YOUR_FILE_ID/view?usp=sharing"
file_id = "1bJLnl6pkQeg5ZpHuTrG8WWEz9YHKVE8n"

# Name for the downloaded file in Colab
output_filename = 'ct_result.xlsx'

gdown.download(id=file_id, output=output_filename, quiet=False)

print(f"File '{output_filename}' downloaded successfully!")

# Now you can load it with pandas
df_raw = pd.read_excel(output_filename)
display(df_raw.head())

Downloading...
From: https://drive.google.com/uc?id=1bJLnl6pkQeg5ZpHuTrG8WWEz9YHKVE8n
To: /content/ct_result.xlsx
100%|██████████| 34.9M/34.9M [00:00<00:00, 82.6MB/s]

File 'ct_result.xlsx' downloaded successfully!

## Translating Korean data to English data
---

*  df_raw['사람_문장_통합']만 뽑아 번역
*  deep_translator 라이브러리의 구글 번역기 사용
* 30000개 넘어가면서 30000~50000 부분의 번역 제대로 되지 않음

In [4]:
!pip install translate

Collecting translate
  Using cached translate-3.8.0-py2.py3-none-any.whl.metadata (9.1 kB)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from translate) (8.3.3)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from translate) (6.1.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from translate) (2.32.4)
Collecting libretranslatepy==2.1.1 (from translate)
  Downloading libretranslatepy-2.1.1-py3-none-any.whl.metadata (233 bytes)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->translate) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->translate) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->translate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->translate) (2026.4.22)
Downloading translate-3.8.0-py2.py3-none-any.whl (14 kB)
Downloading libretranslatepy-2.1.1-py3-none-any.whl (3.2 kB)
Installing collected packages: libretranslatepy, translate
Successfully installed libretranslatepy-2.1.1 translate-3.8.0

In [10]:
# 너무 파일이 커서 안됨....

!pip install translate

import pandas as pd
from translate import Translator
from google.colab import files


# 번역기 세팅
translator = Translator(from_lang='ko', to_lang="en")
# 리스트 컴프리헨션 사용
df = pd.Series([translator.translate(x) for x in df_raw['사람문장_통합']])

# 저장
df.to_excel('t_text.xlsx', index=False)
display(df.head())

files.download('t_text.xlsx')

Requirement already satisfied: translate in /usr/local/lib/python3.12/dist-packages (3.8.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from translate) (8.3.3)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from translate) (6.1.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from translate) (2.32.4)
Requirement already satisfied: libretranslatepy==2.1.1 in /usr/local/lib/python3.12/dist-packages (from translate) (2.1.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->translate) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->translate) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->translate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->translate) (2026.4.22)

HTTPError: 429 Client Error: Too Many Requests for url: https://api.mymemory.translated.net:443/get?q=%EC%9D%B4%EB%B2%88+%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EC%97%90%EC%84%9C+%EB%B0%9C%ED%91%9C%EB%A5%BC+%ED%95%98%EB%8A%94%EB%8D%B0+%EB%82%B4%EA%B0%80+%EC%8B%A4%EC%88%98%ED%95%98%EB%8A%94+%EB%B0%94%EB%9E%8C%EC%97%90+%EC%9A%B0%EB%A6%AC+%ED%8C%80%EC%9D%B4+%EA%B0%90%EC%A0%90%EC%9D%84+%EB%B0%9B%EC%95%98%EC%96%B4.+%EB%84%88%EB%AC%B4+%EB%AF%B8%EC%95%88%ED%95%B4.+%EB%82%B4+%EB%8A%A5%EB%A0%A5%EC%9D%B4+%EB%B6%80%EC%A1%B1%ED%95%9C+%EA%B1%B0+%EA%B0%99%EC%9D%80%EB%8D%B0+%EA%B7%B8%EB%A7%8C+%EB%8B%A4%EB%85%80%EC%95%BC+%EB%90%A0%EA%B1%B0%EA%B0%99%EC%95%84.+%ED%87%B4%EA%B7%BC+%ED%9B%84+%EC%97%AC%EA%B0%80%EC%97%90+%ED%9A%8C%EC%82%AC+%EC%9D%BC%EC%9D%84+%EB%8D%94+%EC%97%B4%EC%8B%AC%ED%9E%88+%ED%95%B4%EC%84%9C+%ED%94%BC%ED%95%B4%EA%B0%80+%EA%B0%80%EC%A7%80+%EC%95%8A%EB%8F%84%EB%A1%9D+%ED%95%B4%EC%95%BC%EA%B2%A0%EC%96%B4.&langpair=ko%7Cen

In [16]:
# 1. 라이브러리 설치 및 가져오기
!pip install deep-translator pandas tqdm openpyxl

import pandas as pd
from deep_translator import GoogleTranslator
from concurrent.futures import ThreadPoolExecutor
from google.colab import files
from tqdm import tqdm

# 진행률 바 활성화
tqdm.pandas()

# 2. 번역기 세팅
translator = GoogleTranslator(source='ko', target='en')

# 안전한 번역을 위한 함수
def safe_translate(text):
    try:
        if pd.isna(text) or str(text).strip() == "": return text
        return translator.translate(str(text))
    except:
        return text

print("병렬 번역을 시작합니다...")

# ThreadPoolExecutor를 사용해 30개씩 동시에 번역
workers = 30
texts = df_raw['사람문장_통합'].tolist()

with ThreadPoolExecutor(max_workers=workers) as executor:
    # tqdm으로 진행률 표시하며 병렬 처리
    translated_texts = list(tqdm(executor.map(safe_translate, texts), total=len(texts)))

df_raw['영어문장_통합'] = translated_texts

# 저장 및 다운로드
df_raw.to_excel('t_result.xlsx', index=False)
files.download('t_result.xlsx')

Requirement already satisfied: deep-translator in /usr/local/lib/python3.12/dist-packages (1.11.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /usr/local/lib/python3.12/dist-packages (from deep-translator) (4.13.5)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from deep-translator) (2.32.4)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2026.4.22)
병렬 번역을 시작합니다...

100%|██████████| 58271/58271 [14:51<00:00, 65.35it/s]

## Q1: Text cleaning

So far we've learned a few text cleaning perations, let's put them together in a function! This function would be a handy one to refer to if you happen to work with some messy text data, and you want to preprocess it with a single function.

Write a function that has at least the following:
- Lowercase the text
- Remove punctuation marks
- Remove extra whitespace characters

In [3]:
def clean_text(text):

  # 기호 list 생성
  from string import punctuation
  import re
  punc = punctuation

  # Step 1: Lowercase
  text = text.lower()

  # Step 2: Use remove_punct to remove punctuation marks
  # text = re.sub(pattern = r'punc', repl = ' ', string = text)
  text = re.sub(pattern =  f"[{re.escape(punc)}]", repl = '', string = text)

  # Step 3: Remove extra whitespace characters
  text = re.sub(pattern = r'\s+', repl = ' ', string = text)

  # Step 4: More cleaning steps?
  text = text.strip()

  return text

In [4]:
# Apply the cleaning function to your text column of the DataFrame
text_column = '영어문장_통합'  # Replace with the actual name of your text column
clean_text_column = 'cleaned_text_eng'  # Name for the new column with cleaned text
df_raw[clean_text_column] = df_raw[text_column].apply(
    lambda x: clean_text(x)
)

display(df_raw[[text_column, clean_text_column]].head())

,영어문장_통합,cleaned_text_eng
0,"During the presentation on this project, I mad...",during the presentation on this project i made...
1,My boss looks so scary that I'm afraid to get ...,my boss looks so scary that im afraid to get c...
2,My boss looks so scary that I'm afraid to get ...,my boss looks so scary that im afraid to get c...
3,This is my first job with great difficulty. Ma...,this is my first job with great difficulty may...
4,I'm worried that my relationship with my colle...,im worried that my relationship with my collea...

In [5]:
# Apply the cleaning function to your text column of the DataFrame
text_column = '사람문장_통합'  # Replace with the actual name of your text column
clean_text_column = 'cleaned_text_ko'  # Name for the new column with cleaned text
df_raw[clean_text_column] = df_raw[text_column].apply(
    lambda x: clean_text(x)
)

display(df_raw[[text_column, clean_text_column]].head())

,사람문장_통합,cleaned_text_ko
0,이번 프로젝트에서 발표를 하는데 내가 실수하는 바람에 우리 팀이 감점을 받았어. 너...,이번 프로젝트에서 발표를 하는데 내가 실수하는 바람에 우리 팀이 감점을 받았어 너무...
1,회사에서 중요한 프로젝트를 혼자 하게 됐는데 솔직히 두렵고 무서워. 나에게 너무 크...,회사에서 중요한 프로젝트를 혼자 하게 됐는데 솔직히 두렵고 무서워 나에게 너무 크게...
2,상사가 너무 무섭게 생겨서 친해지는 게 너무 두려워. 무섭게 생겼는데도 업무를 보려...,상사가 너무 무섭게 생겨서 친해지는 게 너무 두려워 무섭게 생겼는데도 업무를 보려면...
3,이번에 힘들게 들어간 첫 직장이거든. 첫 직장이라서 그런지 너무 긴장된다. 첫 직장...,이번에 힘들게 들어간 첫 직장이거든 첫 직장이라서 그런지 너무 긴장된다 첫 직장이어...
4,직장에서 동료들이랑 관계가 안 좋아질까 봐 걱정돼. 내가 낯가림이 심해서 친해질 수...,직장에서 동료들이랑 관계가 안 좋아질까 봐 걱정돼 내가 낯가림이 심해서 친해질 수 ...

In [6]:
df_raw.head()

,연령,성별,상황키워드,신체질환,감정_대분류,감정_소분류,사람문장1,시스템문장1,사람문장2,시스템문장2,사람문장3,시스템문장3,사람문장_통합,추론_감성_점수,영어문장_통합,cleaned_text_eng,cleaned_text_ko
0,청년,남성,"진로,취업,직장",해당없음,불안,두려운,이번 프로젝트에서 발표를 하는데 내가 실수하는 바람에 우리 팀이 감점을 받았어. 너...,실수하시다니 정말 미안한 마음이 크겠어요.,내 능력이 부족한 거 같은데 그만 다녀야 될거같아.,능력을 올리려면 어떤 방법이 있을까요?,퇴근 후 여가에 회사 일을 더 열심히 해서 피해가 가지 않도록 해야겠어.,꼭 좋은 결과 있길 바라요.,이번 프로젝트에서 발표를 하는데 내가 실수하는 바람에 우리 팀이 감점을 받았어. 너...,-0.682257,"During the presentation on this project, I mad...",during the presentation on this project i made...,이번 프로젝트에서 발표를 하는데 내가 실수하는 바람에 우리 팀이 감점을 받았어 너무...
1,청년,남성,"진로,취업,직장",해당없음,불안,두려운,회사에서 중요한 프로젝트를 혼자 하게 됐는데 솔직히 두렵고 무서워.,큰 프로젝트를 혼자 하셔서 고민이 많겠네요.,나에게 너무 크게 느껴지는 중요한 프로젝트라 버거운 느낌이 들어.,프로젝트를 잘하시기 위해서 어떤 걸 할 수 있나요?,동료 직원에게 도움을 요청해서 같이 해결해야겠어.,동료 직원에게 도움을 요청하기로 하셨군요.,회사에서 중요한 프로젝트를 혼자 하게 됐는데 솔직히 두렵고 무서워. 나에게 너무 크...,-0.688704,My boss looks so scary that I'm afraid to get ...,my boss looks so scary that im afraid to get c...,회사에서 중요한 프로젝트를 혼자 하게 됐는데 솔직히 두렵고 무서워 나에게 너무 크게...
2,청년,남성,"진로,취업,직장",해당없음,불안,두려운,상사가 너무 무섭게 생겨서 친해지는 게 너무 두려워.,직장 상사가 무섭게 생기셔서 친해지는 게 어렵군요.,무섭게 생겼는데도 업무를 보려면 친해져야 할 것 같단말이야.,상사분과 친해질 수 있는 방법은 무엇이 있을까요?,먼저 다가가서 말을 걸어볼게.,직장 상사와 친해지시면 좋겠네요.,상사가 너무 무섭게 생겨서 친해지는 게 너무 두려워. 무섭게 생겼는데도 업무를 보려...,-0.586495,My boss looks so scary that I'm afraid to get ...,my boss looks so scary that im afraid to get c...,상사가 너무 무섭게 생겨서 친해지는 게 너무 두려워 무섭게 생겼는데도 업무를 보려면...
3,청년,남성,"진로,취업,직장",해당없음,불안,두려운,이번에 힘들게 들어간 첫 직장이거든. 첫 직장이라서 그런지 너무 긴장된다.,첫 직장이라서 정말 떨리시고 긴장되실 것 같아요.,첫 직장이어서 잘 적응을 할 수 있을지 모르겠어.,잘 적응 하시려면 무엇을 할 수 있을까요?,직장 동료와 상사들이랑 친하게 지내야겠어.,직장에 잘 적응하시길 바라요.,이번에 힘들게 들어간 첫 직장이거든. 첫 직장이라서 그런지 너무 긴장된다. 첫 직장...,-0.461388,This is my first job with great difficulty. Ma...,this is my first job with great difficulty may...,이번에 힘들게 들어간 첫 직장이거든 첫 직장이라서 그런지 너무 긴장된다 첫 직장이어...
4,청년,남성,"진로,취업,직장",해당없음,불안,두려운,직장에서 동료들이랑 관계가 안 좋아질까 봐 걱정돼.,직장 사람들 관계에 대해서 고민이시군요.,내가 낯가림이 심해서 친해질 수 있을지 모르겠어.,직장 사람들과 친해지려면 무슨 방법이 있을까요?,서로 같은 취미를 공유하고 얘기를 나누다 보면 친해질 수 있을 거 같아.,직장 사람들과 좋은 관계를 가지시길 응원해요.,직장에서 동료들이랑 관계가 안 좋아질까 봐 걱정돼. 내가 낯가림이 심해서 친해질 수...,-0.462224,I'm worried that my relationship with my colle...,im worried that my relationship with my collea...,직장에서 동료들이랑 관계가 안 좋아질까 봐 걱정돼 내가 낯가림이 심해서 친해질 수 ...

In [9]:
from google.colab import files

df_raw.to_excel('ct_result.xlsx', index=False)
files.download('ct_result.xlsx')

## Q2: Should We Remove Stop Words?

Stop-word removal is useful in some NLP tasks, but it can also remove meaningful information.  
In this question, you will decide whether stop-word removal is appropriate for your own dataset.

Choose 10–20 examples from your text column. Then apply tokenization and compare the text before and after stop-word removal.

For English data, use `nltk` or `spaCy` stop-word lists.  
For Korean data, use a custom stop-word list or a morphological analyzer such as `Okt` or `Kiwi`.

Answer the following questions:

1. Remove stop words using one or more methods taught in class.
2. Observe which words were removed. Did stop-word removal help your analysis, or did it remove meaningful information?
3. Writhe whether your would remove stop words in your final analysis? Why or why not?

Your answer should include code, output examples, and a short written justification.

In [3]:
# Kiwi 사용
!pip install kiwipiepy

Collecting kiwipiepy
  Downloading kiwipiepy-0.23.1-cp39-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.3 kB)
Collecting kiwipiepy_model<0.24,>=0.23 (from kiwipiepy)
  Downloading kiwipiepy_model-0.23.0.tar.gz (88.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 9.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from kiwipiepy) (2.0.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kiwipiepy) (4.67.3)
Downloading kiwipiepy-0.23.1-cp39-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 17.0 MB/s eta 0:00:00
Building wheels for collected packages: kiwipiepy_model
  Building wheel for kiwipiepy_model (setup.py) ... done
  Created wheel for kiwipiepy_model: filename=kiwipiepy_model-0.23.0-py3-none-any.whl size=88067826 sha256=98cd3f05e9b8368ac3ad097a238ef789efd533dee685d7726ef0f293be37c9fd
  Stored in directory: /root/.cache/pip/wheels/f2/94/da/ff88b4c2305cd1f3effc8001b5f42f16dc9931bcd84d1e77c3
Successfully built kiwipiepy_model
Installing collected packages: kiwipiepy_model, kiwipiepy
Successfully installed kiwipiepy-0.23.1 kiwipiepy_model-0.23.0

In [6]:
import pandas as pd
from kiwipiepy import Kiwi
from kiwipiepy.utils import Stopwords

# 1. Kiwi 및 불용어 객체 초기화
kiwi = Kiwi()
stopwords = Stopwords()

# 2. 불용어 제거 및 형태소 추출 함수 정의
def remove_stopwords(text):
    # 결측치나 빈 문자열 처리
    if pd.isna(text) or not str(text).strip():
        return ""

    # kiwi.tokenize에 stopwords 객체를 전달하면 자동으로 불용어가 걸러집니다.
    tokens = kiwi.tokenize(str(text), stopwords=stopwords)

    # 걸러진 형태소들의 텍스트만 추출하여 공백으로 연결
    cleaned_tokens = [token.form for token in tokens]
    return " ".join(cleaned_tokens)


# 3. 데이터프레임 컬럼에 함수 적용
df_raw['불용어_제거'] = df_raw['cleaned_text_ko'].apply(remove_stopwords)

# 4. 결과 출력
print(df_raw[['cleaned_text_ko', '불용어_제거']])

                                         cleaned_text_ko  \
0      이번 프로젝트에서 발표를 하는데 내가 실수하는 바람에 우리 팀이 감점을 받았어 너무...
1      회사에서 중요한 프로젝트를 혼자 하게 됐는데 솔직히 두렵고 무서워 나에게 너무 크게...
2      상사가 너무 무섭게 생겨서 친해지는 게 너무 두려워 무섭게 생겼는데도 업무를 보려면...
3      이번에 힘들게 들어간 첫 직장이거든 첫 직장이라서 그런지 너무 긴장된다 첫 직장이어...
4      직장에서 동료들이랑 관계가 안 좋아질까 봐 걱정돼 내가 낯가림이 심해서 친해질 수 ...
...                                                  ...
58266  나이가 먹고 이제 돈도 못 벌어 오니까 어떻게 살아가야 할지 막막해 능력도 없고 아...
58267  몸이 많이 약해졌나 봐 이제 전과 같이 일하지 못할 것 같아 너무 짜증 나 마음 같...
58268  이제 어떻게 해야 할지 모르겠어 남편도 그렇고 노후 준비도 안 되어서 미래가 걱정돼...
58269  몇십 년을 함께 살았던 남편과 이혼했어 그동안의 세월에 배신감을 느끼고 너무 화가 ...
58270  남편과 결혼한 지 사십 년이야 이제 사람 만나는 것도 버겁고 알던 사람도 점점 사라...

                                                  불용어_제거
0      이번 프로젝트 발표 는데 실수 바람 팀 감점 받 너무 미안 능력 부족 거 은데 그만...
1      회사 중요 프로젝트 혼자 는데 솔직히 두렵 무섭 너무 크 느끼 중요 프로젝트 버겁 ...
2      상사 너무 무섭 생기 친하 너무 두렵 무섭 생기 는데 업무 려면 친하 단 야 먼저 ...
3      이번 힘들 들어가 첫 직장 거든 첫 직장 라서 그렇 ᆫ지 너무 긴장 첫 직장 잘 적...
4      직장 동료 이랑 관계 안 좋 ᆯ까 보 걱정 낯가림 심하 친하 있 을지 모르 서로 취...
...                                                  ...
58266  나이 먹 이제 돈 못 벌 오 니까 어떻 살아가 ᆯ지 막막 능력 아무것 무 가치 느끼...
58267  몸 많이 약하 나 보 이제 전 같이 못하 너무 짜증 나 마음 다 있 ᆫ데 이제 몸 ...
58268  이제 어떻 ᆯ지 모르 남편 그렇 노후 준비 안 미래 걱정 주변 다 노후 준비 잘 두...
58269  몇 십 함께 살 남편 이혼 그동안 세월 배신감 느끼 너무 화 나 이제 있 이렇 힘들...
58270  남편 결혼 지 사십 이야 이제 만나 버겁 알 점점 사라지 만나 어렵 자꾸 의심 야 ...

[58271 rows x 2 columns]

In [8]:
df_raw

,연령,성별,상황키워드,신체질환,감정_대분류,감정_소분류,사람문장1,시스템문장1,사람문장2,시스템문장2,사람문장3,시스템문장3,사람문장_통합,추론_감성_점수,영어문장_통합,cleaned_text_eng,cleaned_text_ko,불용어_제거
0,청년,남성,"진로,취업,직장",해당없음,불안,두려운,이번 프로젝트에서 발표를 하는데 내가 실수하는 바람에 우리 팀이 감점을 받았어. 너...,실수하시다니 정말 미안한 마음이 크겠어요.,내 능력이 부족한 거 같은데 그만 다녀야 될거같아.,능력을 올리려면 어떤 방법이 있을까요?,퇴근 후 여가에 회사 일을 더 열심히 해서 피해가 가지 않도록 해야겠어.,꼭 좋은 결과 있길 바라요.,이번 프로젝트에서 발표를 하는데 내가 실수하는 바람에 우리 팀이 감점을 받았어. 너...,-0.682257,"During the presentation on this project, I mad...",during the presentation on this project i made...,이번 프로젝트에서 발표를 하는데 내가 실수하는 바람에 우리 팀이 감점을 받았어 너무...,이번 프로젝트 발표 는데 실수 바람 팀 감점 받 너무 미안 능력 부족 거 은데 그만...
1,청년,남성,"진로,취업,직장",해당없음,불안,두려운,회사에서 중요한 프로젝트를 혼자 하게 됐는데 솔직히 두렵고 무서워.,큰 프로젝트를 혼자 하셔서 고민이 많겠네요.,나에게 너무 크게 느껴지는 중요한 프로젝트라 버거운 느낌이 들어.,프로젝트를 잘하시기 위해서 어떤 걸 할 수 있나요?,동료 직원에게 도움을 요청해서 같이 해결해야겠어.,동료 직원에게 도움을 요청하기로 하셨군요.,회사에서 중요한 프로젝트를 혼자 하게 됐는데 솔직히 두렵고 무서워. 나에게 너무 크...,-0.688704,My boss looks so scary that I'm afraid to get ...,my boss looks so scary that im afraid to get c...,회사에서 중요한 프로젝트를 혼자 하게 됐는데 솔직히 두렵고 무서워 나에게 너무 크게...,회사 중요 프로젝트 혼자 는데 솔직히 두렵 무섭 너무 크 느끼 중요 프로젝트 버겁 ...
2,청년,남성,"진로,취업,직장",해당없음,불안,두려운,상사가 너무 무섭게 생겨서 친해지는 게 너무 두려워.,직장 상사가 무섭게 생기셔서 친해지는 게 어렵군요.,무섭게 생겼는데도 업무를 보려면 친해져야 할 것 같단말이야.,상사분과 친해질 수 있는 방법은 무엇이 있을까요?,먼저 다가가서 말을 걸어볼게.,직장 상사와 친해지시면 좋겠네요.,상사가 너무 무섭게 생겨서 친해지는 게 너무 두려워. 무섭게 생겼는데도 업무를 보려...,-0.586495,My boss looks so scary that I'm afraid to get ...,my boss looks so scary that im afraid to get c...,상사가 너무 무섭게 생겨서 친해지는 게 너무 두려워 무섭게 생겼는데도 업무를 보려면...,상사 너무 무섭 생기 친하 너무 두렵 무섭 생기 는데 업무 려면 친하 단 야 먼저 ...
3,청년,남성,"진로,취업,직장",해당없음,불안,두려운,이번에 힘들게 들어간 첫 직장이거든. 첫 직장이라서 그런지 너무 긴장된다.,첫 직장이라서 정말 떨리시고 긴장되실 것 같아요.,첫 직장이어서 잘 적응을 할 수 있을지 모르겠어.,잘 적응 하시려면 무엇을 할 수 있을까요?,직장 동료와 상사들이랑 친하게 지내야겠어.,직장에 잘 적응하시길 바라요.,이번에 힘들게 들어간 첫 직장이거든. 첫 직장이라서 그런지 너무 긴장된다. 첫 직장...,-0.461388,This is my first job with great difficulty. Ma...,this is my first job with great difficulty may...,이번에 힘들게 들어간 첫 직장이거든 첫 직장이라서 그런지 너무 긴장된다 첫 직장이어...,이번 힘들 들어가 첫 직장 거든 첫 직장 라서 그렇 ᆫ지 너무 긴장 첫 직장 잘 적...
4,청년,남성,"진로,취업,직장",해당없음,불안,두려운,직장에서 동료들이랑 관계가 안 좋아질까 봐 걱정돼.,직장 사람들 관계에 대해서 고민이시군요.,내가 낯가림이 심해서 친해질 수 있을지 모르겠어.,직장 사람들과 친해지려면 무슨 방법이 있을까요?,서로 같은 취미를 공유하고 얘기를 나누다 보면 친해질 수 있을 거 같아.,직장 사람들과 좋은 관계를 가지시길 응원해요.,직장에서 동료들이랑 관계가 안 좋아질까 봐 걱정돼. 내가 낯가림이 심해서 친해질 수...,-0.462224,I'm worried that my relationship with my colle...,im worried that my relationship with my collea...,직장에서 동료들이랑 관계가 안 좋아질까 봐 걱정돼 내가 낯가림이 심해서 친해질 수 ...,직장 동료 이랑 관계 안 좋 ᆯ까 보 걱정 낯가림 심하 친하 있 을지 모르 서로 취...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58266,노년,남성,재정,만성질환 무,분노,성가신,나이가 먹고 이제 돈도 못 벌어 오니까 어떻게 살아가야 할지 막막해. 능력도 없고.,경제적인 문제 때문에 막막하시군요. 마음이 편치 않으시겠어요.,아무것도 할 수 없는 내가 무가치하게 느껴지고 실망스러워.,지금 할 수 있는 가장 합리적인 행동은 무엇인가요?,노년층을 위한 경제적 지원이나 부업 같은 것도 알아보아야겠어.,좋은 결과 얻으시길 바랄게요.,나이가 먹고 이제 돈도 못 벌어 오니까 어떻게 살아가야 할지 막막해. 능력도 없고....,-0.819748,나이가 먹고 이제 돈도 못 벌어 오니까 어떻게 살아가야 할지 막막해. 능력도 없고....,나이가 먹고 이제 돈도 못 벌어 오니까 어떻게 살아가야 할지 막막해 능력도 없고 아...,나이가 먹고 이제 돈도 못 벌어 오니까 어떻게 살아가야 할지 막막해 능력도 없고 아...,나이 먹 이제 돈 못 벌 오 니까 어떻 살아가 ᆯ지 막막 능력 아무것 무 가치 느끼...
58267,노년,여성,재정,만성질환 무,불안,초조한,몸이 많이 약해졌나 봐. 이제 전과 같이 일하지 못할 것 같아 너무 짜증 나.,건강에 대한 어려움 때문에 기분이 좋지 않으시군요. 속상하시겠어요.,마음 같아서는 다 할 수 있는 일인데 이젠 몸이 안 따라와 주니 화만 나.,어떻게 하면 지금의 기분을 나아지게 할 수 있을까요?,남편과 함께 게이트볼이나 치러 가야겠어. 그럼 기분이 나아질 것 같아.,남편과 함께하는 좋은 외출 시간 되시길 바랄게요.,몸이 많이 약해졌나 봐. 이제 전과 같이 일하지 못할 것 같아 너무 짜증 나. 마음...,-0.499678,몸이 많이 약해졌나 봐. 이제 전과 같이 일하지 못할 것 같아 너무 짜증 나. 마음...,몸이 많이 약해졌나 봐 이제 전과 같이 일하지 못할 것 같아 너무 짜증 나 마음 같...,몸이 많이 약해졌나 봐 이제 전과 같이 일하지 못할 것 같아 너무 짜증 나 마음 같...,몸 많이 약하 나 보 이제 전 같이 못하 너무 짜증 나 마음 다 있 ᆫ데 이제 몸 ...
58268,노년,여성,재정,만성질환 무,상처,희생된,이제 어떻게 해야 할지 모르겠어. 남편도 그렇고 노후 준비도 안 되어서 미래가 걱정돼.,노후 준비에 대한 어려움 때문에 걱정이 많으시겠어요.,주변 사람들은 다 노후 준비도 잘해두었던데 난 어떻게 해야 할지 모르겠어. 막막하기...,지금의 상황에서 할 수 있는 가장 좋은 행동이 무엇일까요?,남편과 함께 실버 일자리나 노년층을 위한 국가 지원에 대해 자세히 알아보아야겠어.,좋은 정보 많이 얻으셔서 걱정을 좀 덜으셨으면 좋겠어요.,이제 어떻게 해야 할지 모르겠어. 남편도 그렇고 노후 준비도 안 되어서 미래가 걱정...,-0.443791,이제 어떻게 해야 할지 모르겠어. 남편도 그렇고 노후 준비도 안 되어서 미래가 걱정...,이제 어떻게 해야 할지 모르겠어 남편도 그렇고 노후 준비도 안 되어서 미래가 걱정돼...,이제 어떻게 해야 할지 모르겠어 남편도 그렇고 노후 준비도 안 되어서 미래가 걱정돼...,이제 어떻 ᆯ지 모르 남편 그렇 노후 준비 안 미래 걱정 주변 다 노후 준비 잘 두...
58269,노년,여성,대인관계,만성질환 무,불안,걱정스러운,몇십 년을 함께 살았던 남편과 이혼했어. 그동안의 세월에 배신감을 느끼고 너무 화가 나.,가족과의 문제 때문에 속상하시겠어요.,이제 할 수 있는 일도 없고 이렇게 힘들게 사는 게 불만스럽기만 해.,지금의 감정을 나아지게 할 수 있는 어떤 방법이 있을까요?,함께 친하게 지내던 동네 언니 동생들과 빈자리를 조금이나마 채울까 해.,지인분들과 좋은 시간 보내셨으면 좋겠어요.,몇십 년을 함께 살았던 남편과 이혼했어. 그동안의 세월에 배신감을 느끼고 너무 화가...,-0.907750,몇십 년을 함께 살았던 남편과 이혼했어. 그동안의 세월에 배신감을 느끼고 너무 화가...,몇십 년을 함께 살았던 남편과 이혼했어 그동안의 세월에 배신감을 느끼고 너무 화가 ...,몇십 년을 함께 살았던 남편과 이혼했어 그동안의 세월에 배신감을 느끼고 너무 화가 ...,몇 십 함께 살 남편 이혼 그동안 세월 배신감 느끼 너무 화 나 이제 있 이렇 힘들...
58270,노년,여성,대인관계,만성질환 무,상처,배신당한,남편과 결혼한 지 사십 년이야. 이제 사람 만나는 것도 버겁고 알던 사람도 점점 사라져.,대인관계에 대한 어려움 때문에 걱정되시고 속상하시겠어요.,사람들을 만나는 것이 어려워. 자꾸 사람들을 의심하게만 되고 말이야.,어떻게 하면 지금의 상황에 변화를 만들어낼 수 있을까요?,사람들을 볼 때 의심하고 불신하는 마음을 억눌러야겠어. 사람들을 색안경을 끼고 보지...,원하시는 대로 가지고 계시던 걱정이 잘 해결되셨으면 좋겠어요.,남편과 결혼한 지 사십 년이야. 이제 사람 만나는 것도 버겁고 알던 사람도 점점 사...,-0.843704,남편과 결혼한 지 사십 년이야. 이제 사람 만나는 것도 버겁고 알던 사람도 점점 사...,남편과 결혼한 지 사십 년이야 이제 사람 만나는 것도 버겁고 알던 사람도 점점 사라...,남편과 결혼한 지 사십 년이야 이제 사람 만나는 것도 버겁고 알던 사람도 점점 사라...,남편 결혼 지 사십 이야 이제 만나 버겁 알 점점 사라지 만나 어렵 자꾸 의심 야 ...

In [23]:
import pandas as pd
from kiwipiepy.utils import Stopwords

# 1. 불용어 객체 불러오기
stopwords = Stopwords()

# 2. 불용어 리스트 꺼내기
if hasattr(stopwords, 'stopwords'):
    if isinstance(stopwords.stopwords, dict):
        stopword_list = list(stopwords.stopwords.keys())
    else:
        stopword_list = list(stopwords.stopwords)
else:
    stopword_list = list(stopwords._stopwords)

# 3. 데이터프레임으로 변환
df_stopwords = pd.DataFrame(stopword_list, columns=['형태소', '품사태그'])

# 4. 전체 갯수 및 결과 확인
print(f" Kiwi 불용어 총 갯수: {len(df_stopwords)}개\n")
display(df_stopwords.head(15), df_stopwords.tail(15), df_stopwords)

 Kiwi 불용어 총 갯수: 100개

   형태소 품사태그
0    는   JX
1    월  NNB
2    일  NNB
3    그   NP
4    에  JKB
5    던  ETM
6    의  JKG
7    있   VX
8    때  NNG
9    나   NP
10  부터   JX
11  따르   VV
12   를  JKO
13   중  NNB
14   하  XSV

   형태소 품사태그
85   하  XSA
86   이   MM
87   이  JKC
88   가  JKS
89   겠   EP
90  사람  NNG
91   었   EP
92   을  JKO
93   들  XSN
94   제  XPN
95   고   EC
96   다   EF
97   보   VV
98   은   JX
99   다   EC

   형태소 품사태그
0    는   JX
1    월  NNB
2    일  NNB
3    그   NP
4    에  JKB
..  ..  ...
95   고   EC
96   다   EF
97   보   VV
98   은   JX
99   다   EC

[100 rows x 2 columns]

In [21]:
# Compare the results of before and after stopword removal

# 1. 상위 5개 행만 비교
print("=== 1. 전/후 텍스트 직접 비교 ===")
display(df_raw[['cleaned_text_ko', '불용어_제거']].head()) # 주피터 환경이면 display, 터미널이면 print 사용
print("-" * 50)

# 2. 텍스트 길이(형태소의 갯수) 변화 비교
def count_original_tokens(text):
    if pd.isna(text) or not str(text).strip():
        return 0
    return len(kiwi.tokenize(str(text))) # 기존 문장의 형태소 갯수

def count_cleaned_tokens(text):
    if pd.isna(text) or not str(text).strip():
        return 0
    return len(str(text).split()) # 불용어 제거 후 남은 갯수

df_raw['기존_형태소수'] = df_raw['cleaned_text_ko'].apply(count_original_tokens)
df_raw['제거후_형태소수'] = df_raw['불용어_제거'].apply(count_cleaned_tokens)
df_raw['감소한_갯수'] = df_raw['기존_형태소수'] - df_raw['제거후_형태소수']

print("\n=== 2. 단어(형태소) 수 변화 수치 확인 ===")
display(df_raw[['cleaned_text_ko', '기존_형태소수', '제거후_형태소수', '감소한_갯수']].head())
print("-" * 50)


# 3. 실제로 지워진 불용어 추출
def get_real_removed_words(text):
    if pd.isna(text) or not str(text).strip():
        return ""

    # 1. 불용어 제거 안 한 전체 형태소들
    all_tokens = [t.form for t in kiwi.tokenize(str(text))]
    # 2. 불용어 제거 한 후의 형태소들 (불용어_제거 컬럼과 동일)
    clean_tokens = [t.form for t in kiwi.tokenize(str(text), stopwords=stopwords)]

    # 전체 형태소에서 살아남은 형태소들을 제외한 제거된 불용어들
    removed = [word for word in all_tokens if word not in clean_tokens]

    # 중복 제거 후 쉼표로 연결
    return ", ".join(set(removed))

df_raw['지워진_불용어'] = df_raw['cleaned_text_ko'].apply(get_real_removed_words)

print("\n=== 3. 진짜로 제거된 불용어 확인 ===")
display(df_raw[['cleaned_text_ko', '지워진_불용어']].head())

=== 1. 전/후 텍스트 직접 비교 ===

,cleaned_text_ko,불용어_제거
0,이번 프로젝트에서 발표를 하는데 내가 실수하는 바람에 우리 팀이 감점을 받았어 너무...,이번 프로젝트 발표 는데 실수 바람 팀 감점 받 너무 미안 능력 부족 거 은데 그만...
1,회사에서 중요한 프로젝트를 혼자 하게 됐는데 솔직히 두렵고 무서워 나에게 너무 크게...,회사 중요 프로젝트 혼자 는데 솔직히 두렵 무섭 너무 크 느끼 중요 프로젝트 버겁 ...
2,상사가 너무 무섭게 생겨서 친해지는 게 너무 두려워 무섭게 생겼는데도 업무를 보려면...,상사 너무 무섭 생기 친하 너무 두렵 무섭 생기 는데 업무 려면 친하 단 야 먼저 ...
3,이번에 힘들게 들어간 첫 직장이거든 첫 직장이라서 그런지 너무 긴장된다 첫 직장이어...,이번 힘들 들어가 첫 직장 거든 첫 직장 라서 그렇 ᆫ지 너무 긴장 첫 직장 잘 적...
4,직장에서 동료들이랑 관계가 안 좋아질까 봐 걱정돼 내가 낯가림이 심해서 친해질 수 ...,직장 동료 이랑 관계 안 좋 ᆯ까 보 걱정 낯가림 심하 친하 있 을지 모르 서로 취...

--------------------------------------------------

=== 2. 단어(형태소) 수 변화 수치 확인 ===

,cleaned_text_ko,기존_형태소수,제거후_형태소수,감소한_갯수
0,이번 프로젝트에서 발표를 하는데 내가 실수하는 바람에 우리 팀이 감점을 받았어 너무...,65,26,39
1,회사에서 중요한 프로젝트를 혼자 하게 됐는데 솔직히 두렵고 무서워 나에게 너무 크게...,53,22,31
2,상사가 너무 무섭게 생겨서 친해지는 게 너무 두려워 무섭게 생겼는데도 업무를 보려면...,47,20,27
3,이번에 힘들게 들어간 첫 직장이거든 첫 직장이라서 그런지 너무 긴장된다 첫 직장이어...,47,26,21
4,직장에서 동료들이랑 관계가 안 좋아질까 봐 걱정돼 내가 낯가림이 심해서 친해질 수 ...,57,24,33

--------------------------------------------------

=== 3. 진짜로 제거된 불용어 확인 ===

,cleaned_text_ko,지워진_불용어
0,이번 프로젝트에서 발표를 하는데 내가 실수하는 바람에 우리 팀이 감점을 받았어 너무...,"을, 않, 더, 어, 되, 에, 겠, 에서, 어야, 우리, 일, 의, 를, 었, 는..."
1,회사에서 중요한 프로젝트를 혼자 하게 됐는데 솔직히 두렵고 무서워 나에게 너무 크게...,"을, 에게, 어, 은, 되, 겠, 에서, 어야, 게, 를, 었, 고, 는, 이, 지..."
2,상사가 너무 무섭게 생겨서 친해지는 게 너무 두려워 무섭게 생겼는데도 업무를 보려면...,"하, 가, 었, 도, 을, 것, 같, 어야, 는, 게, 어서, 말, 어, 이, ᆯ,..."
3,이번에 힘들게 들어간 첫 직장이거든 첫 직장이라서 그런지 너무 긴장된다 첫 직장이어...,"하, 에, 을, ᆫ, ᆫ다, 겠, 어야, 들, 게, 어서, 와, 수, 어, 이, ᆯ, 되"
4,직장에서 동료들이랑 관계가 안 좋아질까 봐 걱정돼 내가 낯가림이 심해서 친해질 수 ...,"을, 어, 은, 면, 되, 가, 겠, 에서, 들, 다, 를, 고, 이, ᆯ, 지, ..."

In [22]:
df_raw

,연령,성별,상황키워드,신체질환,감정_대분류,감정_소분류,사람문장1,시스템문장1,사람문장2,시스템문장2,...,cleaned_text_ko,불용어_제거,기존_단어수,제거후_단어수,감소한_단어수,지워진_단어들,기존_형태소수,제거후_형태소수,감소한_갯수,지워진_불용어
0,청년,남성,"진로,취업,직장",해당없음,불안,두려운,이번 프로젝트에서 발표를 하는데 내가 실수하는 바람에 우리 팀이 감점을 받았어. 너...,실수하시다니 정말 미안한 마음이 크겠어요.,내 능력이 부족한 거 같은데 그만 다녀야 될거같아.,능력을 올리려면 어떤 방법이 있을까요?,...,이번 프로젝트에서 발표를 하는데 내가 실수하는 바람에 우리 팀이 감점을 받았어 너무...,이번 프로젝트 발표 는데 실수 바람 팀 감점 받 너무 미안 능력 부족 거 은데 그만...,33,26,7,"해서, 가지, 부족한, 팀이, 더, 내, 일을, 발표를, 받았어, 실수하는, 여가에...",65,26,39,"을, 않, 더, 어, 되, 에, 겠, 에서, 어야, 우리, 일, 의, 를, 었, 는..."
1,청년,남성,"진로,취업,직장",해당없음,불안,두려운,회사에서 중요한 프로젝트를 혼자 하게 됐는데 솔직히 두렵고 무서워.,큰 프로젝트를 혼자 하셔서 고민이 많겠네요.,나에게 너무 크게 느껴지는 중요한 프로젝트라 버거운 느낌이 들어.,프로젝트를 잘하시기 위해서 어떤 걸 할 수 있나요?,...,회사에서 중요한 프로젝트를 혼자 하게 됐는데 솔직히 두렵고 무서워 나에게 너무 크게...,회사 중요 프로젝트 혼자 는데 솔직히 두렵 무섭 너무 크 느끼 중요 프로젝트 버겁 ...,24,22,2,"요청해서, 버거운, 해결해야겠어, 무서워, 프로젝트라, 직원에게, 두렵고, 도움을,...",53,22,31,"을, 에게, 어, 은, 되, 겠, 에서, 어야, 게, 를, 었, 고, 는, 이, 지..."
2,청년,남성,"진로,취업,직장",해당없음,불안,두려운,상사가 너무 무섭게 생겨서 친해지는 게 너무 두려워.,직장 상사가 무섭게 생기셔서 친해지는 게 어렵군요.,무섭게 생겼는데도 업무를 보려면 친해져야 할 것 같단말이야.,상사분과 친해질 수 있는 방법은 무엇이 있을까요?,...,상사가 너무 무섭게 생겨서 친해지는 게 너무 두려워 무섭게 생겼는데도 업무를 보려면...,상사 너무 무섭 생기 친하 너무 두렵 무섭 생기 는데 업무 려면 친하 단 야 먼저 ...,20,20,0,"다가가서, 생겨서, 것, 두려워, 말을, 친해지는, 게, 무섭게, 생겼는데도, 친해...",47,20,27,"하, 가, 었, 도, 을, 것, 같, 어야, 는, 게, 어서, 말, 어, 이, ᆯ,..."
3,청년,남성,"진로,취업,직장",해당없음,불안,두려운,이번에 힘들게 들어간 첫 직장이거든. 첫 직장이라서 그런지 너무 긴장된다.,첫 직장이라서 정말 떨리시고 긴장되실 것 같아요.,첫 직장이어서 잘 적응을 할 수 있을지 모르겠어.,잘 적응 하시려면 무엇을 할 수 있을까요?,...,이번에 힘들게 들어간 첫 직장이거든 첫 직장이라서 그런지 너무 긴장된다 첫 직장이어...,이번 힘들 들어가 첫 직장 거든 첫 직장 라서 그렇 ᆫ지 너무 긴장 첫 직장 잘 적...,23,26,-3,"있을지, 직장이거든, 동료와, 지내야겠어, 이번에, 들어간, 그런지, 모르겠어, 수...",47,26,21,"하, 에, 을, ᆫ, ᆫ다, 겠, 어야, 들, 게, 어서, 와, 수, 어, 이, ᆯ, 되"
4,청년,남성,"진로,취업,직장",해당없음,불안,두려운,직장에서 동료들이랑 관계가 안 좋아질까 봐 걱정돼.,직장 사람들 관계에 대해서 고민이시군요.,내가 낯가림이 심해서 친해질 수 있을지 모르겠어.,직장 사람들과 친해지려면 무슨 방법이 있을까요?,...,직장에서 동료들이랑 관계가 안 좋아질까 봐 걱정돼 내가 낯가림이 심해서 친해질 수 ...,직장 동료 이랑 관계 안 좋 ᆯ까 보 걱정 낯가림 심하 친하 있 을지 모르 서로 취...,26,24,2,"공유하고, 있을지, 동료들이랑, 친해질, 낯가림이, 걱정돼, 봐, 좋아질까, 내가,...",57,24,33,"을, 어, 은, 면, 되, 가, 겠, 에서, 들, 다, 를, 고, 이, ᆯ, 지, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58266,노년,남성,재정,만성질환 무,분노,성가신,나이가 먹고 이제 돈도 못 벌어 오니까 어떻게 살아가야 할지 막막해. 능력도 없고.,경제적인 문제 때문에 막막하시군요. 마음이 편치 않으시겠어요.,아무것도 할 수 없는 내가 무가치하게 느껴지고 실망스러워.,지금 할 수 있는 가장 합리적인 행동은 무엇인가요?,...,나이가 먹고 이제 돈도 못 벌어 오니까 어떻게 살아가야 할지 막막해 능력도 없고 아...,나이 먹 이제 돈 못 벌 오 니까 어떻 살아가 ᆯ지 막막 능력 아무것 무 가치 느끼...,29,26,3,"지원이나, 능력도, 나이가, 없는, 오니까, 것도, 무가치하게, 노년층을, 아무것도...",63,26,37,"을, 적, 어, 은, 가, 겠, 도, 없, 어야, 게, 고, 는, 위하, ᆯ, 지,..."
58267,노년,여성,재정,만성질환 무,불안,초조한,몸이 많이 약해졌나 봐. 이제 전과 같이 일하지 못할 것 같아 너무 짜증 나.,건강에 대한 어려움 때문에 기분이 좋지 않으시군요. 속상하시겠어요.,마음 같아서는 다 할 수 있는 일인데 이젠 몸이 안 따라와 주니 화만 나.,어떻게 하면 지금의 기분을 나아지게 할 수 있을까요?,...,몸이 많이 약해졌나 봐 이제 전과 같이 일하지 못할 것 같아 너무 짜증 나 마음 같...,몸 많이 약하 나 보 이제 전 같이 못하 너무 짜증 나 마음 다 있 ᆫ데 이제 몸 ...,38,33,5,"기분이, 일인데, 나아질, 봐, 치러, 같아서는, 주니, 전과, 이젠, 약해졌나, ...",71,33,38,"하, 었, 겠, ᆫ, 것, 같, 어야, 는, 주, 어서, 수, 과, 일, 어, 만,..."
58268,노년,여성,재정,만성질환 무,상처,희생된,이제 어떻게 해야 할지 모르겠어. 남편도 그렇고 노후 준비도 안 되어서 미래가 걱정돼.,노후 준비에 대한 어려움 때문에 걱정이 많으시겠어요.,주변 사람들은 다 노후 준비도 잘해두었던데 난 어떻게 해야 할지 모르겠어. 막막하기...,지금의 상황에서 할 수 있는 가장 좋은 행동이 무엇일까요?,...,이제 어떻게 해야 할지 모르겠어 남편도 그렇고 노후 준비도 안 되어서 미래가 걱정돼...,이제 어떻 ᆯ지 모르 남편 그렇 노후 준비 안 미래 걱정 주변 다 노후 준비 잘 두...,37,33,4,"사람들은, 걱정돼, 노년층을, 해, 알아보아야겠어, 해야, 모르겠어, 난, 할지, ...",77,33,44,"을, 어, 은, 만, 되, 에, 가, 겠, 도, 어야, 들, 게, 대하, 었, 고,..."
58269,노년,여성,대인관계,만성질환 무,불안,걱정스러운,몇십 년을 함께 살았던 남편과 이혼했어. 그동안의 세월에 배신감을 느끼고 너무 화가 나.,가족과의 문제 때문에 속상하시겠어요.,이제 할 수 있는 일도 없고 이렇게 힘들게 사는 게 불만스럽기만 해.,지금의 감정을 나아지게 할 수 있는 어떤 방법이 있을까요?,...,몇십 년을 함께 살았던 남편과 이혼했어 그동안의 세월에 배신감을 느끼고 너무 화가 ...,몇 십 함께 살 남편 이혼 그동안 세월 배신감 느끼 너무 화 나 이제 있 이렇 힘들...,35,31,4,"년을, 이혼했어, 이렇게, 몇십, 살았던, 세월에, 불만스럽기만, 해, 게, 느끼고...",69,31,38,"던, 을, 어, 만, 에, 가, 도, 없, 들, 게, 일, 의, 를, 었, 고, 는..."
58270,노년,여성,대인관계,만성질환 무,상처,배신당한,남편과 결혼한 지 사십 년이야. 이제 사람 만나는 것도 버겁고 알던 사람도 점점 사라져.,대인관계에 대한 어려움 때문에 걱정되시고 속상하시겠어요.,사람들을 만나는 것이 어려워. 자꾸 사람들을 의심하게만 되고 말이야.,어떻게 하면 지금의 상황에 변화를 만들어낼 수 있을까요?,...,남편과 결혼한 지 사십 년이야 이제 사람 만나는 것도 버겁고 알던 사람도 점점 사라...,남편 결혼 지 사십 이야 이제 만나 버겁 알 점점 사라지 만나 어렵 자꾸 의심 야 ...,35,22,13,"볼, 끼고, 만나는, 의심하게만, 의심하고, 때, 것도, 사람도, 사람들을, 어려워...",75,22,53,"던, 을, 않, 보, 때, 어, 만, 되, 겠, 도, 어야, 들, 게, 고, 는, ..."

In [15]:
from google.colab import files

df_raw.to_excel('st_result.xlsx', index=False)
files.download('st_result.xlsx')

Your answer whether you would remove stop words in your final analysis? Why or why not?
**Answer:**
불용어를 제거하지 않을 것 입니다. 다국어 LLM의 한국어 감정 인식 성능을 보는 연구를 하기 때문에, 불용어를 포함한 문장 자체에서 나타나는 감정을 LLM이 어떻게 인식하는지 봐야하기 때문입니다. 그러나, 저희 데이터가 긍정적인 감정보다 부정적인 감정에 치우쳐있기 때문에 [감정_대분류]가 기쁨인 문장들에 불용어를 제거하는 처리를 한후 기존 데이터에 증강을 해주어 균형을 맞추는 방법은 고려해볼만한 것 같습니다.

## Q3: Choose a Tokenizer for Your Own Text Data

Tokenization is one of the most important steps in text preprocessing. However, there is no single tokenizer that works best for every dataset. The best choice depends on the language, text source, and analysis goal.

Choose 10–20 examples from your own text column and inspect them carefully. Then compare different tokenization methods.

Answer the following questions:

1. What is the language of your data? If your data contains Korean, why might simple whitespace tokenization be insufficient?

2. What kind of text is it? For example: survey responses, social media posts, interviews, reviews, news articles, academic abstracts, or mixed sources.

3. Apply at least two tokenization methods to the same 5–10 text examples.  
   - For English data, you may compare methods such as:
     - whitespace tokenization
     - NLTK `word_tokenize`
     - spaCy tokenizer
     - a BERT tokenizer
   - For Korean data, you may compare methods such as:
     - whitespace tokenization
     - `Okt`
     - `Kiwi`
     - `Komoran`
     - `Kkma`
     - a Korean BERT tokenizer

4. Compare the outputs. What differences do you notice? Consider:
   - Are words split in a useful way?
   - Are particles, endings, punctuation, or symbols handled appropriately?
   - Are unknown words, slang, abbreviations, or domain-specific terms handled well?
   - Does the tokenizer preserve information that may be important for your analysis?

5. Which tokenizer would you choose for your dataset, and why?

Your answer should include:
- code that applies at least two tokenizers,
- tokenized output for several examples,
- a short written justification for your final tokenizer choice.

In [3]:
# 라이브러리 설치
!pip install kiwipiepy
!pip install konlpy
!pip install transformers
!pip install torch

Requirement already satisfied: kiwipiepy in /usr/local/lib/python3.12/dist-packages (0.23.1)
Requirement already satisfied: kiwipiepy_model<0.24,>=0.23 in /usr/local/lib/python3.12/dist-packages (from kiwipiepy) (0.23.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from kiwipiepy) (2.0.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kiwipiepy) (4.67.3)
Requirement already satisfied: konlpy in /usr/local/lib/python3.12/dist-packages (0.6.0)
Requirement already satisfied: JPype1>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from konlpy) (1.7.1)
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from konlpy) (6.1.0)
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.12/dist-packages (from konlpy) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from JPype1>=0.7.0->konlpy) (26.1)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.29.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cu128)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Collecting sympy>=1.13.3 (from torch)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch) (1.5.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 73.7 MB/s eta 0:00:00
Installing collected packages: sympy
  Attempting uninstall: sympy
    Found existing installation: sympy 1.12
    Uninstalling sympy-1.12:
      Successfully uninstalled sympy-1.12
Successfully installed sympy-1.14.0

In [29]:
!pip install sympy==1.12

Collecting sympy==1.12
  Downloading sympy-1.12-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.12/dist-packages (from sympy==1.12) (1.3.0)
Downloading sympy-1.12-py3-none-any.whl (5.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 79.8 MB/s eta 0:00:00
Installing collected packages: sympy
  Attempting uninstall: sympy
    Found existing installation: sympy 1.14.0
    Uninstalling sympy-1.14.0:
      Successfully uninstalled sympy-1.14.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.10.0+cu128 requires sympy>=1.13.3, but you have sympy 1.12 which is incompatible.
Successfully installed sympy-1.12

In [ ]:
import pandas as pd
from tqdm import tqdm

# Fix: Upgrade sympy to resolve compatibility issues with torch
!pip install --upgrade sympy

from kiwipiepy import Kiwi
from konlpy.tag import Okt, Komoran, Kkma
from transformers import AutoTokenizer

# 진행 상태바(tqdm)를 pandas의 apply와 연동
tqdm.pandas()

print("1. 토크나이저 및 모델 초기화 중 (시간이 조금 걸릴 수 있습니다)...")
kiwi = Kiwi()
okt = Okt()
komoran = Komoran()
kkma = Kkma()
# KLUE-BERT 토크나이저 로드 (Hugging Face)
bert_tokenizer = AutoTokenizer.from_pretrained("klue/bert-base")

# 2. 안전한 토크나이징 함수 정의
def get_kiwi_tokens(text):
    if not isinstance(text, str) or not str(text).strip(): return []
    return [token.form for token in kiwi.tokenize(text)]

def get_okt_tokens(text):
    if not isinstance(text, str) or not str(text).strip(): return []
    return okt.morphs(text, norm=True, stem=True)

def get_komoran_tokens(text):
    if not isinstance(text, str) or not str(text).strip(): return []
    try: return komoran.morphs(text)
    except: return []

def get_kkma_tokens(text):
    if not isinstance(text, str) or not str(text).strip(): return []
    try: return kkma.morphs(text)
    except: return []

def get_bert_tokens(text):
    if not isinstance(text, str) or not str(text).strip(): return []
    # BERT는 .tokenize()를 사용해 서브워드(Subword) 단위로 분리합니다.
    return bert_tokenizer.tokenize(text)


print("\n2. 데이터프레임 토크나이징 적용 시작...")
target_columns = ['사람문장_통합', 'cleaned_text_ko']

for col in target_columns:
    # 만약 해당 컬럼이 데이터프레임에 없다면 건너뜀니다.
    if col not in df_raw.columns:
        continue

    print(f"\n[{col}] 컬럼 처리 중...")

    print("  - Kiwi 적용 중...")
    df_raw[f'{col}_kiwi'] = df_raw[col].progress_apply(get_kiwi_tokens)

    print("  - Okt 적용 중...")
    df_raw[f'{col}_okt'] = df_raw[col].progress_apply(get_okt_tokens)

    print("  - Komoran 적용 중...")
    df_raw[f'{col}_komoran'] = df_raw[col].progress_apply(get_komoran_tokens)

    print("  - KLUE-BERT 적용 중...")
    df_raw[f'{col}_bert'] = df_raw[col].progress_apply(get_bert_tokens)

print("토크나이징 완료")

Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (1.14.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy) (1.3.0)
1. 토크나이저 및 모델 초기화 중 (시간이 조금 걸릴 수 있습니다)...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/425 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/289 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

2. 데이터프레임 토크나이징 적용 시작...

[사람문장_통합] 컬럼 처리 중...
  - Kiwi 적용 중...

100%|██████████| 58271/58271 [03:00<00:00, 323.35it/s]

  - Okt 적용 중...

100%|██████████| 58271/58271 [11:00<00:00, 88.28it/s]

  - Komoran 적용 중...

100%|██████████| 58271/58271 [02:34<00:00, 377.41it/s]

  - KLUE-BERT 적용 중...

100%|██████████| 58271/58271 [00:09<00:00, 5996.23it/s]

  - Kkma 적용 중

  1%|▏         | 864/58271 [02:26<1:38:30,  9.71it/s]

In [2]:
df_raw

NameError: name 'df_raw' is not defined

Your answer which tokenizer you think is better for your data and task

**Answer:**

# 4. What else? (bonus point)